# Job Declarator Server config for testnet4 production

# Async Job Support
async_mining_allowed = true

# SRI Pool config
authority_public_key = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"
authority_secret_key = "mkDLTBBRxdBv998612qipDYoTK3YUrqLe8uWw7gu3iXbSrn2n"
cert_validity_sec = 3600

# Coinbase reward script (specified as a descriptor)
# For more info on descriptors see: https://github.com/bitcoin/bips/blob/master/bip-0380.mediawiki#appendix-b-index-of-script-expressions
coinbase_reward_script = "addr(tb1qa0sm0hxzj0x25rh8gw5xlzwlsfvvyz8u96w3p8)"

# JD Server listening address
listen_jd_address = "127.0.0.1:34264"

# Template Provider listening address for JDC connections
listen_tp_address = "127.0.0.1:8442"

# Stats server config (TCP address for stats-pool service)
stats_server_address = "127.0.0.1:9083"

# Bitcoin Core RPC config for mempool access
core_rpc_url = "http://127.0.0.1"
core_rpc_port = 48332
core_rpc_user = "username"
core_rpc_pass = "password"

# Time interval for JDS mempool update
[mempool_update_interval]
unit = "secs"
value = 1
