# SRI Pool config for testnet4 production
authority_public_key = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"
authority_secret_key = "mkDLTBBRxdBv998612qipDYoTK3YUrqLe8uWw7gu3iXbSrn2n"
cert_validity_sec = 3600
listen_address = "0.0.0.0:34254"

# List of coinbase outputs used to build the coinbase tx
# For P2PK, P2PKH, P2WPKH, P2TR a public key is needed. For P2SH and P2WSH, a redeem script is needed.
coinbase_outputs = [
    { output_script_type = "P2WPKH", output_script_value = "036adc3bdf21e6f9a0f0fb0066bf517e5b7909ed1563d6958a10993849a7554075" },
]

# Pool signature (string to be included in coinbase tx)
pool_signature = "Hashpool Testnet"

# Template Provider config - using local TP
tp_address = "127.0.0.1:8442"

# Stats server config (TCP address for stats-pool service)
stats_server_address = "127.0.0.1:4000"

# Job Declarator Server address
jd_server_address = "127.0.0.1:34264"
