# Local Mining Device Downstream Connection
# Dev - use your local network IP or 0.0.0.0 to listen on all interfaces
# downstream_address = "0.0.0.0"
# downstream_port = 34255
# Prod - VPS external IP
downstream_address = "188.40.233.11"
downstream_port = 34256

# Version support
max_supported_version = 2
min_supported_version = 2

# Minimum extranonce2 size for downstream
# Max value: 16 (leaves 0 bytes for search space splitting of downstreams)
# Max value for CGminer: 8
# Min value: 2
downstream_extranonce2_size = 8

# User identity for upstream connection
user_identity = "hashpool"

# Aggregate all downstream miners into single upstream channel
aggregate_channels = false

# Stats server config (TCP address for stats-proxy)
stats_server_address = "127.0.0.1:8082"

# Redact miner IP addresses from database and website (prod)
redact_ip = true

# Faucet configuration
faucet_port = 8083
faucet_timeout = 3

# Primary upstream pool server (for web-proxy connection display)
upstream_address = "127.0.0.1"
upstream_port = 34254

# List of upstream pool servers (with fallback support)
[[upstreams]]
# Local SRI JDC Upstream Connection
address = "127.0.0.1"
port = 34254
authority_pubkey = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"

# Alternative upstream (commented out)
# [[upstreams]]
# Braiins Pool Upstream Connection
# address = "18.196.32.109"
# port = 3336
# authority_pubkey = "u95GEReVMjK6k5YqiSFNqqTnKU4ypU2Wm8awa6tmbmDmk1bWt"

# Difficulty params
[downstream_difficulty_config]
# Minimum hashrate is derived automatically from shared minimum_difficulty to prevent
# downstream targets from dropping below the mint's ehash threshold.
# target number of shares per minute the miner should be sending
shares_per_minute = 6.0
# enable variable difficulty adjustment mechanism
# if false, difficulty will be managed by upstream (useful with JDC)
enable_vardiff = true

[upstream_difficulty_config]
# interval in seconds to elapse before updating channel hashrate with the pool
channel_diff_update_interval = 60
# estimated accumulated hashrate of all downstream miners (e.g.: 10 Th/s = 10_000_000_000_000.0)
channel_nominal_hashrate = 10_000_000.0

[wallet]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
db_path = ".devenv/state/translator/wallet.sqlite"
locking_privkey = "e1c193b1a2681f01a10731f317c754a031ed9e61aaaf702b5083e55a2c0a8fff"
