[workspace]

resolver="2"

members = [
    "mining-proxy",
    "pool",
    "stats-pool",
    "stats-proxy",
    "test-utils/mining-device",
    "test-utils/mining-device-sv1",
    "translator",
    "jd-client",
    "jd-server",
    "tests-integration",
    "mint",
    "roles-utils/mint-pool-messaging",
    "roles-utils/quote-dispatcher",
    "roles-utils/web-assets", "roles-utils/stats",
]

[profile.dev]
# Required by super_safe_lock
opt-level = 1

[profile.test]
# Required by super_safe_lock
opt-level = 1

[workspace.dependencies]
hyper = "=0.14.32"
