[workspace]

resolver="2"

members = [
    "ehash",
    "v1",
    "v2/subprotocols/mint-quote",
    "v2/subprotocols/stats-sv2",
    "v2/roles-logic-sv2",
    "v2/parsers-sv2",
    "v2/handlers-sv2",
]


[patch.crates-io]
cashu           = { git = "https://github.com/vnprc/cdk", rev = "cba8469b" }
cdk             = { git = "https://github.com/vnprc/cdk", rev = "cba8469b" }
cdk-common      = { git = "https://github.com/vnprc/cdk", rev = "cba8469b" }
cdk-http-client = { git = "https://github.com/vnprc/cdk", rev = "cba8469b" }
cdk-signatory   = { git = "https://github.com/vnprc/cdk", rev = "cba8469b" }
cdk-sql-common  = { git = "https://github.com/vnprc/cdk", rev = "cba8469b" }
cdk-sqlite      = { git = "https://github.com/vnprc/cdk", rev = "cba8469b" }

[profile.dev]
# Required by super_safe_lock
opt-level = 1

[profile.test]
# Required by super_safe_lock
opt-level = 1
