# SRI JDC config
listening_address = "127.0.0.1:34265"

# Version support
max_supported_version = 2
min_supported_version = 2

# Auth keys for open encrypted connection downstream
authority_public_key = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"
authority_secret_key = "mkDLTBBRxdBv998612qipDYoTK3YUrqLe8uWw7gu3iXbSrn2n"
cert_validity_sec = 3600

# User identity/username for pool connection
user_identity = "your_username_here"

# Target number of shares per minute applied to every downstream channel
shares_per_minute = 6.0

# Share batch size
share_batch_size = 10

# Min extranonce size
min_extranonce_size = 4

# JDC supports two modes:
# "FULLTEMPLATE"  - full template mining
# "COINBASEONLY" - coinbase-only mining
mode = "FULLTEMPLATE"

# Template Provider config
# Local TP (this is pointing to localhost so you must run a TP locally for this configuration to work)
tp_address = "127.0.0.1:8442"
# Hosted testnet TP
# tp_address = "75.119.150.111:8442"

# String to be added into the Coinbase scriptSig
jdc_signature = "Sv2MinerSignature"

# Solo Mining config
# Coinbase output used to build the coinbase tx in case of Solo Mining (as last-resort solution of the pools fallback system)
# Coinbase outputs are specified as descriptors. A full list of descriptors is available at
#     https://github.com/bitcoin/bips/blob/master/bip-0380.mediawiki#appendix-b-index-of-script-expressions
# Although the `musig` descriptor is not yet supported and the legacy `combo` descriptor never will be.
# If you have an address, embed it in a descriptor like `addr(<address here>)`.
coinbase_reward_script = "addr(tb1qa0sm0hxzj0x25rh8gw5xlzwlsfvvyz8u96w3p8)"

[timeout]
unit = "secs"
value = 1

# List of upstreams (JDS) used as backup endpoints
# In case of shares refused by the JDS, the fallback system will propose the same job to the next upstream in this list
[[upstreams]]
authority_pubkey = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"
pool_address = "127.0.0.1"
pool_port = 34254
jds_address = "127.0.0.1"
jds_port = 34264
