[redis]
host = "localhost"
port = 6379
url = "redis://localhost:6379"

# redis keys
create_quote_prefix = "mint:quotes:create"
active_keyset_prefix = "mint:keyset:active"

[mint]
host = "localhost"
port = 3338
url = "http://localhost:3338"

[pool]
port = 34254

[proxy]
port = 34255

[bitcoin]
# network set by var in devenv.nix
portRegtest = "18443"
portTestnet = "48332"