
[sv2_messaging]
# SV2 messaging configuration for pool-mint communication
enabled = true
# TCP listener for mint connections (separate from mining device listener)
mint_listen_address = "127.0.0.1:34260" 
broadcast_buffer_size = 1000
mpsc_buffer_size = 100
max_retries = 3
timeout_ms = 5000

[mint]
host = "localhost"
port = 3338
url = "http://localhost:3338"
# host = "mint.hashpool.dev"
# port = 443
# url = "https://mint.hashpool.dev"

[pool]
port = 34254

[proxy]
port = 34255

[bitcoin]
# network set by var in devenv.nix
portRegtest = "18443"
portTestnet = "48332"

[ehash]
# TODO: This should be retrieved dynamically from the mint
# Minimum difficulty (leading zero bits) required to earn 1 unit of ehash
minimum_difficulty = 32
