
[sv2_messaging]
# SV2 messaging configuration for pool-mint communication
enabled = true
# TCP listener for mint connections (separate from mining device listener)
mint_listen_address = "127.0.0.1:34260" 
broadcast_buffer_size = 1000
mpsc_buffer_size = 100
max_retries = 3
timeout_ms = 5000

[mint]
host = "localhost"
port = 3338
url = "http://localhost:3338"

[pool]
port = 34254

[proxy]
port = 34255

[bitcoin]
# network set by var in devenv.nix
portRegtest = "18443"
portTestnet = "48332"